ibm: &ibm IBM Plex Mono:pixelsize=12

bg_default: &bg_default { stack: [{ background: { color: 524f67ff } }] }

# This is THE bar configuration
bar:
  height: 26
  location: top
  spacing: 3
  right-margin: 8

  # Default font
  font: *ibm

  foreground: e0def4ff
  background: 191724d8

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 13
              right-margin: 13
              default: { string: { text: , font: *ibm } }
              conditions:
                id == 1: { string: { text: 1, font: *ibm } }
                id == 2: { string: { text: 2, font: *ibm } }
                id == 3: { string: { text: 3, font: *ibm } }
                id == 4: { string: { text: 4, font: *ibm } }
                id == 5: { string: { text: 5, font: *ibm } }
                id == 6: { string: { text: 6, font: *ibm } }
                id == 7: { string: { text: 7, font: *ibm } }
                id == 8: { string: { text: 8, font: *ibm } }
                id == 9: { string: { text: 9, font: *ibm } }

        content:
          map:
            conditions:
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: { empty: {} }
              state == invisible && occupied:
                map:
                  <<: *river_base
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: { empty: {} }
              activated:
                - string: { text: "{app-id}", left-margin: 5 }

  center:
    - clock:
        time-format: "%R"
        content:
          - string: { text: "{time}" }

  right:
    - mem:
        poll-interval: 2500
        content:
          - string: { text: "mem: {used:mb}/{total:mb}mb", right-margin: 4 }
          - string: { text: "|", foreground: 908caaff }

    - cpu:
        poll-interval: 2500
        content:
          map:
            conditions:
              id < 0:
                - string: { text: "cpu: {cpu}%", right-margin: 4 }
                - string: { text: "|", foreground: 908caaff }
    - battery:
        name: BAT1
        poll-interval: 30000
        content:
          - string: { text: "bat: {capacity}%", right-margin: 4 }
          - string: { text: "|", foreground: 908caaff }
    - clock:
        date-format: "%A, %d %b"
        content:
          string: { text: "{date}" }
